name: Cambio en Documentaci贸n
description: Crea una tarea para cualquier cambio, mejora o correcci贸n en la documentaci贸n del proyecto.
title: "[Docs]: "
labels: [docs]
assignees:
  - "" # Asignaci贸n manual o con GitHub Actions
body:
  - type: markdown
    attributes:
      value: |
        ##  Cambio en la Documentaci贸n
        Completa este formulario con los detalles sobre el cambio que necesitas realizar en la documentaci贸n del proyecto. Esto incluye correcciones, actualizaciones o mejoras.

  - type: input
    id: docs-summary
    attributes:
      label:  Resumen del Cambio
      placeholder: "Ej: Corregir la secci贸n de instalaci贸n en README"
      description: |
        Proporciona un resumen breve del cambio o correcci贸n que se debe realizar en la documentaci贸n.

  - type: textarea
    id: description
    attributes:
      label:  Descripci贸n Detallada
      description: |
        Explica en detalle qu茅 es lo que se necesita cambiar en la documentaci贸n. Esto puede incluir correcci贸n de errores tipogr谩ficos, actualizaci贸n de versiones, adici贸n de nuevas secciones, etc.  
        Para m谩s detalles sobre c贸mo redactar cambios en la documentaci贸n, consulta [Mejores Pr谩cticas de Documentaci贸n](https://www.writethedocs.org/guide/) (Haz clic derecho para abrir en una nueva pesta帽a).
      placeholder: |
        Este cambio consiste en corregir la secci贸n de instalaci贸n en el archivo README, ya que los pasos no son compatibles con la 煤ltima versi贸n.
    validations:
      required: true

  - type: input
    id: docs-file
    attributes:
      label:  Archivo Afectado
      placeholder: "Ej: README.md, docs/installation.md, gdrive link"
      description: |
        Indica el archivo(s) espec铆fico(s) que necesita(n) ser actualizado(s) o corregido(s).  
        Si no est谩s seguro, menciona la secci贸n de la documentaci贸n que necesitas cambiar.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label:  Contexto Adicional
      description: |
        Si tienes alg煤n contexto adicional que deba conocerse antes de realizar el cambio, por favor descr铆belo aqu铆. Esto puede incluir detalles sobre por qu茅 se est谩 haciendo el cambio, o referencias a problemas previos.
    validations:
      required: false

  - type: checkboxes
    id: definition-of-ready
    attributes:
      label: Ь Confirmaci贸n de la Definici贸n de Listo
      description: |
        Por favor, confirma que esta tarea cumple con nuestra [Definici贸n de Listo](https://microsoft.github.io/code-with-engineering-playbook/agile-development/team-agreements/definition-of-ready/) (Haz clic derecho para abrir en una nueva pesta帽a).
      options:
        - label: Confirmo que esta tarea contiene suficiente informaci贸n para ser procesada.
          required: false
